import turtle
window = turtle.Screen()
pen = turtle.Turtle()
window.bgcolor("skyblue")
pen.pensize(2)

#Boat
pen.up()
pen.right(90)
pen.forward(150)
pen.left(90)
pen.down()
pen.begin_fill()
pen.fillcolor("red")
pen.forward(80)
pen.left(180)
pen.forward(160)
pen.left(90)
pen.circle(80, 180)
pen.end_fill()
pen.left(90)
pen.up()
pen.forward(80)
pen.down()
pen.right(90)
pen.forward(110)
pen.begin_fill()
pen.fillcolor("white")
for i in range(2):
    pen.left(120)
    pen.forward(70)
pen.end_fill()

#Ocean
pen.up()
pen.goto(-390, -230)
pen.left(30)
pen.down()
pen.color("blue")
pen.begin_fill()
pen.fillcolor("blue")
pen.forward(770)
pen.right(90)
pen.forward(90)
pen.right(90)
pen.forward(770)
pen.right(90)
pen.forward(90)
pen.end_fill()

#Rainbow
r = 196
x = 200
pen.pensize(6)
pen.up()
pen.goto(190, -225)

for aColor in ["violet", "indigo", "blue", "green", "yellow", "orange", "red"]:
    pen.down()
    pen.color(aColor)
    pen.circle(x, 180)
    x = x + 6 
    pen.up()
    pen.goto(r, -225)
    r = r + 6
    pen.left(180)

#Sunshine
pen.up()
pen.goto(-250, 230)
pen.down()
pen.color("yellow")
pen.begin_fill()
pen.fillcolor("yellow")
pen.circle(60)
pen.end_fill()

#Clouds
pen.up()
pen.goto(280, 180)
pen.down()
pen.color("white")
pen.begin_fill()
pen.fillcolor("white")
for i in range(2):
    pen.circle(20, 180)
    pen.right(180)
    pen.circle(20,180)
    pen.right(90)
    pen.circle(20,180)
    pen.right(90)
pen.end_fill()

pen.up()
pen.goto(0, 230)
pen.down()
pen.color("white")
pen.begin_fill()
pen.fillcolor("white")
for i in range(2):
    pen.circle(20, 180)
    pen.right(180)
    pen.circle(20,180)
    pen.right(90)
    pen.circle(20,180)
    pen.right(90)
pen.end_fill()

pen.up()
pen.goto(-230, 90)
pen.down()
pen.color("white")
pen.begin_fill()
pen.fillcolor("white")
for i in range(2):
    pen.circle(20, 180)
    pen.right(180)
    pen.circle(20,180)
    pen.right(90)
    pen.circle(20,180)
    pen.right(90)
pen.end_fill()

#Fish
pen.up()
pen.pensize(2)
pen.goto(-250, -280)
pen.down()
pen.color("orchid")
pen.begin_fill()
pen.fillcolor("orchid")
pen.circle(15)
pen.end_fill()
pen.begin_fill()
pen.fillcolor("orchid")
pen.right(60)
for i in range(2):
    pen.forward(20)
    pen.right(120)
    pen.forward(20)
    pen.right(120)
pen.end_fill()
pen.color("black")
pen.up()
pen.goto(-275, -280)
pen.down()
pen.begin_fill()
pen.fillcolor("black")
pen.circle(2)
pen.end_fill()

pen.up()
pen.goto(-100,-260)
pen.down()
pen.color("yellow")
pen.begin_fill()
pen.fillcolor("yellow")
pen.circle(7)
pen.end_fill()
pen.begin_fill()
pen.fillcolor("yellow")
pen.right(60)
for i in range(2):
    pen.forward(10)
    pen.right(120)
    pen.forward(10)
    pen.right(120)
pen.end_fill()
pen.color("black")
pen.up()
pen.goto(-90, -260)
pen.down()
pen.begin_fill()
pen.fillcolor("black")
pen.circle(0.6)
pen.end_fill()

pen.up()
pen.goto(130,-300)
pen.down()
pen.color("deep sky blue")
pen.begin_fill()
pen.fillcolor("deep sky blue")
pen.circle(10)
pen.end_fill()
pen.begin_fill()
pen.fillcolor("deep sky blue")
pen.right(60)
for i in range(2):
    pen.forward(15)
    pen.right(120)
    pen.forward(15)
    pen.right(120)
pen.end_fill()
pen.color("black")
pen.up()
pen.goto(115, -300)
pen.down()
pen.begin_fill()
pen.fillcolor("black")
pen.circle(1)
pen.end_fill()

pen.up()
pen.goto(250,-270)
pen.down()
pen.color("medium spring green")
pen.begin_fill()
pen.fillcolor("medium spring green")
pen.circle(20)
pen.end_fill()
pen.begin_fill()
pen.fillcolor("medium spring green")
pen.right(60)
for i in range(2):
    pen.forward(21)
    pen.right(120)
    pen.forward(21)
    pen.right(120)
pen.end_fill()
pen.color("black")
pen.up()
pen.goto(285, -270)
pen.down()
pen.begin_fill()
pen.fillcolor("black")
pen.circle(2.5)
pen.end_fill()


#Boat Name
pen.up()
pen.goto(15,-170)
pen.down()
pen.write("S.S. Bunting")


window.exitonclick()